import { BadRequestException, ConflictException, Injectable, NotFoundException } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { DataSource, Repository } from "typeorm";
import { Cocktail, CocktailStatus } from "../cocktails/entities/cocktail.entity";
import { CocktailReviewLog } from "../cocktails/entities/cocktail-review-log.entity";
import { User, UserStatus } from "../users/entities/user.entity";
import { AdminAuditLog } from "./entities/audit-log.entity";
import { Role } from "./entities/role.entity";
import { UserRole } from "./entities/user-role.entity";
import { AdminCocktailQueryDto, AdminUserQueryDto, UpdateUserStatusDto } from "./dto/admin.dto";
import { RedisService } from "../redis/redis.service";
import { CocktailRevision } from "../cocktails/entities/cocktail-revision.entity";

@Injectable()
export class AdminService {
  constructor(private readonly dataSource: DataSource, @InjectRepository(User) private readonly users: Repository<User>, @InjectRepository(Cocktail) private readonly cocktails: Repository<Cocktail>, @InjectRepository(CocktailReviewLog) private readonly reviewLogs: Repository<CocktailReviewLog>, @InjectRepository(CocktailRevision) private readonly revisions: Repository<CocktailRevision>, @InjectRepository(Role) private readonly roles: Repository<Role>, @InjectRepository(UserRole) private readonly userRoles: Repository<UserRole>, private readonly redis: RedisService) {}
  async usersList(q: AdminUserQueryDto) { const qb = this.users.createQueryBuilder("u"); if (q.status) qb.where("u.status = :status", { status: q.status }); if (q.search) qb.andWhere("(u.email ILIKE :search OR u.name ILIKE :search)", { search: `%${q.search}%` }); const [data, total] = await qb.orderBy("u.createdAt", "DESC").skip((q.page - 1) * q.limit).take(q.limit).getManyAndCount(); return { __paged: true, data: data.map(({ passwordHash, ...u }) => u), meta: { page: q.page, limit: q.limit, total } }; }
  async userDetail(id: string) { const user = await this.users.findOneBy({ id }); if (!user) throw new NotFoundException("User not found"); const [roles, cocktailCount] = await Promise.all([this.userRoles.find({ where: { user: { id } }, relations: { role: true } }), this.cocktails.count({ where: { owner: { id } } })]); return { ...user, roles: roles.map((x) => x.role), cocktailCount }; }
  async cocktailsList(q: AdminCocktailQueryDto) { const where: any = { ...(q.status ? { status: q.status } : {}), ...(q.ownerId ? { owner: { id: q.ownerId } } : {}) }; const [data, total] = await this.cocktails.findAndCount({ where, relations: { owner: true, reviewer: true, category: true }, order: { createdAt: "DESC" }, skip: (q.page - 1) * q.limit, take: q.limit }); return { __paged: true, data, meta: { page: q.page, limit: q.limit, total } }; }
  async cocktailDetail(id: string) { const cocktail = await this.cocktails.findOne({ where: { id }, relations: { owner: true, reviewer: true, category: true } }); if (!cocktail) throw new NotFoundException("Cocktail not found"); const [reviewLogs, revisions] = await Promise.all([this.reviewLogs.find({ where: { cocktail: { id } }, relations: { reviewer: true }, order: { createdAt: "DESC" } }), this.revisions.find({ where: { cocktail: { id } }, relations: { author: true, reviewer: true }, order: { createdAt: "DESC" } })]); return { cocktail, revisions, reviewLogs }; }
  async removeCocktail(actorId: string, id: string) { const cocktail = await this.cocktails.findOneBy({ id }); if (!cocktail) throw new NotFoundException("Cocktail not found"); await this.dataSource.transaction(async (m) => { await m.softRemove(cocktail); await this.audit(m, actorId, "cocktails.delete", "cocktail", id, { status: cocktail.status }, null); }); await this.invalidateCocktailCache(); return { id }; }
  async auditLogs(q: AdminUserQueryDto) { const [data, total] = await this.dataSource.getRepository(AdminAuditLog).findAndCount({ relations: { actor: true }, order: { createdAt: "DESC" }, skip: (q.page - 1) * q.limit, take: q.limit }); return { __paged: true, data, meta: { page: q.page, limit: q.limit, total } }; }
  async listRoles() { return this.roles.find({ order: { code: "ASC" } }); }
  async setUserStatus(actorId: string, id: string, dto: UpdateUserStatusDto) { const user = await this.users.findOneBy({ id }); if (!user) throw new NotFoundException("User not found"); if (id === actorId && dto.status === UserStatus.DISABLED) throw new ConflictException("You cannot disable yourself"); if (dto.status === UserStatus.DISABLED) { const current = await this.userRoles.find({ where: { user: { id } }, relations: { role: true } }); if (current.some((x) => x.role.code === "super_admin")) { const activeAdmins = await this.userRoles.createQueryBuilder("ur").innerJoin("ur.role", "role", "role.code = :code", { code: "super_admin" }).innerJoin("ur.user", "user", "user.status = :status", { status: UserStatus.ACTIVE }).getCount(); if (activeAdmins <= 1) throw new ConflictException("The last active super admin cannot be disabled"); } } const before = { status: user.status, disabledAt: user.disabledAt, disabledReason: user.disabledReason }; user.status = dto.status; user.disabledAt = dto.status === UserStatus.DISABLED ? new Date() : null; user.disabledReason = dto.status === UserStatus.DISABLED ? dto.reason || null : null; await this.dataSource.transaction(async (m) => { await m.save(user); await this.audit(m, actorId, "users.update_status", "user", id, before, { status: user.status, disabledReason: user.disabledReason }); }); return user; }
  async review(actorId: string, id: string, action: "approve" | "reject" | "offline" | "publish", reason?: string) { const x = await this.cocktails.findOne({ where: { id }, relations: { reviewer: true } }); if (!x) throw new NotFoundException("Cocktail not found"); const from = x.status; const requiredReason = action === "reject" || action === "offline"; if (requiredReason && !reason) throw new BadRequestException("reason is required"); const target: Record<string, CocktailStatus> = { approve: CocktailStatus.PUBLISHED, reject: CocktailStatus.REJECTED, offline: CocktailStatus.OFFLINE, publish: CocktailStatus.PUBLISHED }; const allowed: Record<string, CocktailStatus[]> = { approve: [CocktailStatus.PENDING], reject: [CocktailStatus.PENDING], offline: [CocktailStatus.PUBLISHED], publish: [CocktailStatus.OFFLINE] }; if (!allowed[action].includes(from)) throw new ConflictException("Invalid cocktail status transition"); const reviewer = await this.users.findOneBy({ id: actorId }); if (!reviewer) throw new NotFoundException("Reviewer not found"); x.status = target[action]; x.reviewer = reviewer; x.reviewedAt = new Date(); if (action === "approve" || action === "publish") { x.publishedAt = new Date(); x.rejectReason = null; x.offlineReason = null; } if (action === "reject") x.rejectReason = reason!; if (action === "offline") x.offlineReason = reason!; await this.dataSource.transaction(async (m) => { await m.save(x); await m.save(CocktailReviewLog, m.create(CocktailReviewLog, { cocktail: x, action, fromStatus: from, toStatus: x.status, reviewer, reason: reason || null })); await this.audit(m, actorId, `cocktails.${action}`, "cocktail", id, { status: from }, { status: x.status, reason: reason || null }); }); await this.invalidateCocktailCache(); return x; }
  async replaceRoles(actorId: string, userId: string, roleIds: string[]) { const [user, actor, roles] = await Promise.all([this.users.findOneBy({ id: userId }), this.users.findOneBy({ id: actorId }), this.roles.findByIds(roleIds)]); if (!user || !actor) throw new NotFoundException("User not found"); if (roles.length !== new Set(roleIds).size) throw new BadRequestException("One or more roles do not exist"); const actorRoles = await this.userRoles.find({ where: { user: { id: actorId } }, relations: { role: true } }); if (!actorRoles.some((x) => x.role.code === "super_admin")) throw new ConflictException("Only super admins can assign roles"); const current = await this.userRoles.find({ where: { user: { id: userId } }, relations: { role: true } }); const removesSuperAdmin = current.some((x) => x.role.code === "super_admin") && !roles.some((x) => x.code === "super_admin"); if (removesSuperAdmin) { const total = await this.userRoles.createQueryBuilder("ur").innerJoin("ur.role", "role", "role.code = :code", { code: "super_admin" }).getCount(); if (total <= 1) throw new ConflictException("The last super admin role cannot be removed"); } await this.dataSource.transaction(async (m) => { await m.delete(UserRole, { user: { id: userId } }); if (roles.length) await m.save(UserRole, roles.map((role) => m.create(UserRole, { user, role, assignedBy: actor }))); await this.audit(m, actorId, "users.assign_roles", "user", userId, null, { roleIds }); }); }
  private async audit(m: any, actorId: string, action: string, targetType: string, targetId: string, before: object | null, after: object | null) { const actor = await m.findOneBy(User, { id: actorId }); await m.save(AdminAuditLog, m.create(AdminAuditLog, { actor, action, targetType, targetId, before, after })); }
  private async invalidateCocktailCache() { await Promise.all([this.redis.del("list:v1:*"), this.redis.del("list:v2:*"), this.redis.del("list:v3:*"), this.redis.del("rec:v1:*")]); }
}
