import { MigrationInterface, QueryRunner } from "typeorm";

export class AddAdminRbacAndCocktailReview1750000000000 implements MigrationInterface {
  name = "AddAdminRbacAndCocktailReview1750000000000";
  async up(q: QueryRunner) {
    await q.query(`CREATE EXTENSION IF NOT EXISTS "pgcrypto"`);
    await q.query(`CREATE TYPE "public"."users_status_enum" AS ENUM ('active', 'disabled')`);
    await q.query(`ALTER TABLE "users" ADD "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', ADD "disabledAt" timestamptz, ADD "disabledReason" varchar(255)`);
    await q.query(`CREATE TYPE "public"."cocktails_status_enum" AS ENUM ('draft', 'pending', 'rejected', 'published', 'offline')`);
    await q.query(`ALTER TABLE "cocktails" ADD "status" "public"."cocktails_status_enum" NOT NULL DEFAULT 'draft', ADD "submittedAt" timestamptz, ADD "reviewedAt" timestamptz, ADD "reviewerId" uuid, ADD "rejectReason" varchar(500), ADD "publishedAt" timestamptz, ADD "offlineReason" varchar(500)`);
    await q.query(`ALTER TABLE "cocktails" ADD CONSTRAINT "FK_cocktails_reviewer" FOREIGN KEY ("reviewerId") REFERENCES "users"("id") ON DELETE SET NULL`);
    await q.query(`UPDATE "cocktails" SET "status" = CASE WHEN "isPrivate" THEN 'draft'::"public"."cocktails_status_enum" ELSE 'published'::"public"."cocktails_status_enum" END, "publishedAt" = CASE WHEN "isPrivate" THEN NULL ELSE "createdAt" END`);
    await q.query(`CREATE INDEX "IDX_cocktails_status_created" ON "cocktails" ("status", "createdAt" DESC)`);
    await q.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "code" varchar(64) NOT NULL, "name" varchar(128) NOT NULL, "description" text, "isSystem" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_roles" PRIMARY KEY ("id"), CONSTRAINT "UQ_roles_code" UNIQUE ("code"))`);
    await q.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "code" varchar(96) NOT NULL, "name" varchar(128) NOT NULL, CONSTRAINT "PK_permissions" PRIMARY KEY ("id"), CONSTRAINT "UQ_permissions_code" UNIQUE ("code"))`);
    await q.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "userId" uuid NOT NULL, "roleId" uuid NOT NULL, "assignedById" uuid, "createdAt" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_user_roles" PRIMARY KEY ("id"), CONSTRAINT "UQ_user_roles" UNIQUE ("userId", "roleId"), CONSTRAINT "FK_user_roles_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE, CONSTRAINT "FK_user_roles_role" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE, CONSTRAINT "FK_user_roles_actor" FOREIGN KEY ("assignedById") REFERENCES "users"("id") ON DELETE SET NULL)`);
    await q.query(`CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "roleId" uuid NOT NULL, "permissionId" uuid NOT NULL, CONSTRAINT "PK_role_permissions" PRIMARY KEY ("id"), CONSTRAINT "UQ_role_permissions" UNIQUE ("roleId", "permissionId"), CONSTRAINT "FK_role_permissions_role" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE, CONSTRAINT "FK_role_permissions_permission" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE CASCADE)`);
    await q.query(`CREATE TABLE "cocktail_review_logs" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "cocktailId" varchar(32) NOT NULL, "action" varchar(32) NOT NULL, "fromStatus" "public"."cocktails_status_enum", "toStatus" "public"."cocktails_status_enum", "reviewerId" uuid, "reason" varchar(500), "createdAt" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_cocktail_review_logs" PRIMARY KEY ("id"), CONSTRAINT "FK_review_cocktail" FOREIGN KEY ("cocktailId") REFERENCES "cocktails"("id") ON DELETE CASCADE, CONSTRAINT "FK_review_user" FOREIGN KEY ("reviewerId") REFERENCES "users"("id") ON DELETE SET NULL)`);
    await q.query(`CREATE TABLE "admin_audit_logs" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "actorId" uuid, "action" varchar(96) NOT NULL, "targetType" varchar(64) NOT NULL, "targetId" varchar(64) NOT NULL, "before" jsonb, "after" jsonb, "createdAt" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_admin_audit_logs" PRIMARY KEY ("id"), CONSTRAINT "FK_audit_actor" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE SET NULL)`);
    await q.query(`CREATE INDEX "IDX_review_cocktail_created" ON "cocktail_review_logs" ("cocktailId", "createdAt" DESC)`);
    await q.query(`CREATE INDEX "IDX_audit_target_created" ON "admin_audit_logs" ("targetType", "targetId", "createdAt" DESC)`);
    await q.query(`INSERT INTO "permissions" ("code", "name") VALUES ('users.read','Read users'), ('users.update_status','Update user status'), ('users.assign_roles','Assign user roles'), ('cocktails.read','Read cocktails'), ('cocktails.review','Review cocktails'), ('cocktails.publish','Publish cocktails'), ('cocktails.offline','Offline cocktails'), ('cocktails.update','Update cocktails'), ('cocktails.delete','Delete cocktails'), ('roles.read','Read roles'), ('roles.manage','Manage roles'), ('audit_logs.read','Read audit logs')`);
    await q.query(`INSERT INTO "roles" ("code", "name", "description") VALUES ('super_admin','Super administrator','Full administrative access'), ('operator','Operator','User and content operations'), ('reviewer','Reviewer','Content review only'), ('user','User','Client user')`);
    await q.query(`INSERT INTO "role_permissions" ("roleId", "permissionId") SELECT r."id", p."id" FROM "roles" r CROSS JOIN "permissions" p WHERE r."code" = 'super_admin'`);
    await q.query(`INSERT INTO "role_permissions" ("roleId", "permissionId") SELECT r."id", p."id" FROM "roles" r JOIN "permissions" p ON p."code" IN ('users.read','users.update_status','cocktails.read','cocktails.publish','cocktails.offline','cocktails.update','cocktails.delete') WHERE r."code" = 'operator'`);
    await q.query(`INSERT INTO "role_permissions" ("roleId", "permissionId") SELECT r."id", p."id" FROM "roles" r JOIN "permissions" p ON p."code" IN ('cocktails.read','cocktails.review') WHERE r."code" = 'reviewer'`);
  }
  async down(q: QueryRunner) {
    await q.query(`DROP TABLE "admin_audit_logs"`); await q.query(`DROP TABLE "cocktail_review_logs"`); await q.query(`DROP TABLE "role_permissions"`); await q.query(`DROP TABLE "user_roles"`); await q.query(`DROP TABLE "permissions"`); await q.query(`DROP TABLE "roles"`);
    await q.query(`DROP INDEX "IDX_cocktails_status_created"`); await q.query(`ALTER TABLE "cocktails" DROP CONSTRAINT "FK_cocktails_reviewer"`); await q.query(`ALTER TABLE "cocktails" DROP COLUMN "offlineReason", DROP COLUMN "publishedAt", DROP COLUMN "rejectReason", DROP COLUMN "reviewerId", DROP COLUMN "reviewedAt", DROP COLUMN "submittedAt", DROP COLUMN "status"`); await q.query(`DROP TYPE "public"."cocktails_status_enum"`);
    await q.query(`ALTER TABLE "users" DROP COLUMN "disabledReason", DROP COLUMN "disabledAt", DROP COLUMN "status"`); await q.query(`DROP TYPE "public"."users_status_enum"`);
  }
}
